// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvqujxwtbukewzxtxema.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2cXVqeHd0YnVrZXd6eHR4ZW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzMxODQsImV4cCI6MjA1OTAwOTE4NH0.1_5t55CT5zuuPfAzI91L3jkMccgxoiJGwB1ewSxS6WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);